### PR TITLE
Upgrade mock

### PR DESCRIPTION
**Pull request by ekmartin**

### CODE REVIEW

**Comment by frecar** [comment]
What should we do with this?

**Comment by relekang** [comment]
Fix it :)

**Comment by frecar** [comment]
hehe indeed :)

**Comment by relekang** [comment]
Looks like mock finally detects when you call wrongly named assert functions.

**Comment by relekang** [comment]
It should be good now :)

**Comment by frecar** [comment]
Great work! :dancers:

**Pull request merged**
